Repository stolostron/siteconfig, pull requests merged in 2024-08, with the labels that each got.

#52 CNF-13858: Fix default IBI cluster templates
  internal/templates/image-based-install/template.go
Labels: lgtm, approved

#56 CNF-13885: Cleanup bundle/manifests
  bundle/manifests/siteconfig-controller-manager-metrics-service_v1alpha1_service.yaml
  bundle/manifests/siteconfig-controller-manager_v1alpha1_serviceaccount.yaml
  bundle/manifests/siteconfig-metrics-reader_rbac.authorization.k8s.io_v1alpha1_clusterrole.yaml
Labels: lgtm, approved

#57 CNF-13877: Remove infraenv label from default IBI cluster template
  internal/templates/image-based-install/template.go
Labels: lgtm, approved

#53 CNF-13857: Add documention for configuring GitOps Flow with the SiteConfig Operator
  docs/argocd.md
Labels: lgtm, approved

#59 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/siteconfig-main-pull-request.yaml
  .tekton/siteconfig-main-push.yaml
Labels: lgtm, approved, ok-to-test, dco-signoff: yes

#60 CNF-14021: Migrate buildah from 0.1 to 0.2
  .tekton/siteconfig-main-pull-request.yaml
  .tekton/siteconfig-main-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#58 CNF-13987: Add ObservedGeneration to ClusterInstance.Status
  api/v1alpha1/clusterinstance_types.go
  bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
  config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
  internal/controller/clusterdeployment_reconciler.go
  internal/controller/clusterdeployment_reconciler_test.go
  internal/controller/clusterinstance_controller.go
  internal/controller/clusterinstance_controller_test.go
  internal/controller/conditions/conditions.go
  internal/controller/conditions/conditions_test.go
Labels: lgtm, approved, dco-signoff: yes

#66 CNF-14123: Add preprovisioningNetworkDataName BMH support
  internal/templates/image-based-install/template.go
Labels: lgtm, approved, dco-signoff: yes

#68 CNF-14190: Add pruneManifests to ClusterInstance CRD
  api/v1alpha1/clusterinstance_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
  config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
Labels: lgtm, approved, dco-signoff: yes

#71 CNF-14191: Add owned-by label to rendered manifests
  internal/controller/clusterinstance/helper.go
  internal/controller/clusterinstance/helper_test.go
  internal/controller/clusterinstance/template_engine.go
  internal/controller/clusterinstance/template_engine_test.go
Labels: lgtm, approved, dco-signoff: yes

#75 CNF-13357: Enable extra labels to be configured through ClusterInstance
  api/v1alpha1/clusterinstance_types.go
  api/v1alpha1/clusterinstance_utils.go
  api/v1alpha1/clusterinstance_utils_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
  config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
  internal/controller/clusterinstance/template_engine.go
  internal/controller/clusterinstance/template_engine_test.go
Labels: lgtm, approved, dco-signoff: yes
