Repository stolostron/siteconfig, pull requests merged in 2025-01, with the labels that each got.

#164 CNF-16324: kustomize: Replace patchesStrategicMerge with patches
  config/default/kustomization.yaml
Labels: lgtm, approved, dco-signoff: yes

#167 ACM-16896: Refactor createOrPatch to handle objects without spec fields
  internal/controller/clusterinstance_controller.go
  internal/controller/clusterinstance_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#155 CNF-15745: Add data preservation functionality to the SiteConfig Operator
  docs/preservation.md
  internal/controller/preservation/helper.go
  internal/controller/preservation/helper_test.go
  internal/controller/preservation/preservation.go
  internal/controller/preservation/preservation_test.go
  internal/controller/preservation/suite_test.go
Labels: lgtm, approved, ok-to-test, dco-signoff: yes

#168 ACM-16625: Upversion golang.org/x/ dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test, dco-signoff: yes

#166 ACM-16360: Remove resource limits from SiteConfig Operator deployment
  bundle/manifests/siteconfig.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, approved, dco-signoff: yes

#173 ACM-17042: Address EnterpriseContract Konflux violations
  .tekton/siteconfig-acm-212-pull-request.yaml
  .tekton/siteconfig-acm-212-push.yaml
  .tekton/siteconfig-acm-213-pull-request.yaml
  .tekton/siteconfig-acm-213-push.yaml
  .tekton/siteconfig-main-pull-request.yaml
  .tekton/siteconfig-main-push.yaml
  Dockerfile
Labels: lgtm, approved, ok-to-test, dco-signoff: yes

#172 CNF-16397: Fix misspell and gofmt issues detected by Go Report Card
  internal/controller/clusterinstance_controller_test.go
  internal/controller/configuration_monitor_test.go
Labels: lgtm, approved, dco-signoff: yes

#165 Update Go toolchain to 1.22.9
  Dockerfile
  go.mod
Labels: lgtm, approved, ok-to-test, dco-signoff: yes

#175 Use go-version-file in Github workflow
  .github/workflows/ci-job.yml
Labels: approved, ok-to-test, dco-signoff: yes

#176 Upversion metal3-io/baremetal-operator/apis from 0.8.0 to 0.9.0
  go.mod
  go.sum
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/doc.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/hostfirmwaresettings_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/hostupdatepolicy_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, dco-signoff: yes

#177 CNF-16436: Add CPUArchitecture fields to ClusterInstanceSpec and NodeSpec CRDs
  api/v1alpha1/clusterinstance_types.go
  bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
  config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
Labels: lgtm, approved, ok-to-test, dco-signoff: yes

#180 CNF-16467: Add some badges to README.md
  README.md
Labels: lgtm, approved, dco-signoff: yes

#181 CNF-16469: Fix GolangCI Configuration and Apply Linters
  .golangci.yml
  api/v1alpha1/clusterinstance_types.go
  api/v1alpha1/clusterinstance_utils.go
  cmd/main.go
  internal/controller/clusterdeployment_reconciler.go
  internal/controller/clusterinstance/helper.go
  internal/controller/clusterinstance/ownership.go
  internal/controller/clusterinstance/rendered_object.go
  internal/controller/clusterinstance/template_engine.go
  internal/controller/clusterinstance/test_utils.go
  internal/controller/clusterinstance_controller.go
  internal/controller/configuration_monitor.go
  internal/controller/deletion/deletion.go
  internal/controller/errors/errors.go
  internal/controller/preservation/helper.go
  internal/controller/preservation/preservation.go
  internal/templates/image-based-installer/template.go
Labels: lgtm, approved, dco-signoff: yes
